services:
  - type: Static-Site
    name: coding-application-fe
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: NODE_VERSION
        value: 18.20.3
      - key: REACT_APP_API_URL
        value: "https://coding-application-be.onrender.com/api"
